theme: jekyll-theme-minimal
title: Christian Thor Møller's homepage
description: Hello :) I am an AI Engineer @ Laerdal Copenhagen. This page will be for posting side projects, or other posts I find interesting.
